hydra:
  run:
    dir: ./${dataset.name}/${model.name}/${prior.name}/TEST
  sweep:
    dir: ./${dataset.name}/${model.name}/${prior.name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - dataset
          - prior

defaults:
  - dataset: 3D_low
  - prior: None
  - model: osem
seed: 1
num_images: 1
