hydra:
  run:
    dir: ./${dataset.name}/${model.name}/${prior.name}
  sweep:
    dir: ./${dataset.name}/${model.name}/${prior.name}
    subdir: ${hydra.job.override_dirname}
  job:
    config:
      override_dirname:
        exclude_keys:
          - dataset
          - prior

defaults:
  - dataset: 2D_high
  - prior: None
  - model: baseline
seed: 1
num_images: 1
