arch:
  scales: 3
  channels: [64, 64, 64]
  skip_channels: [0, 4, 4]
  use_norm: True
  use_relu: True
optim:
  lr: 5e-4
  iterations: 10000
  loss_function: poisson
show_pbar: True
torch_manual_seed: 10
log_path: ./
load_pretrain_model: False
recon_from_randn: True