hydra:
  run:
    dir: ./${now:%Y-%m-%d}/${now:%H-%M-%S}/${dataset.name}/${prior.name}
  sweep:
    dir: ./${now:%Y-%m-%d}/${now:%H-%M-%S}/${dataset.name}/${prior.name}
    subdir: ${hydra.job.override_dirname}

defaults:
  - dataset: 2D
  - prior: OSEM
